In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('survey.csv')
df.head()

,Timestamp,Gender,Age group,Profession,Average screen time on daily basis (phone or laptop),Average time spent on social media on daily basis,What's your most used social media platform?,Your content-format preference while using Instagram,Your content-format preference while using Youtube,What kind of content do you prefer?,Do you feel that consuming short-form content has reduced your ability to focus on longer tasks or content?,How long can you stay focused on a task without getting distracted?,Do you find it difficult to focus on longer videos or read articles after consuming short-form content?,Do you feel addicted to these platforms and short-length contents?,How do you feel after spending time watching short-form videos?,Have you ever tried to reduce the time spent on short-form videos?,Has it affected your productivity in terms of work and life?
0,2025-01-14 23:49:12.926,Male,20-30,Employed,6-8 hours,< 2 hours,Instagram,Reels (under 20 seconds),Videos (< 10mins),"Entertainment, Comedy",Maybe,5-10 mins,No,Sometimes,Neutral,Yes and i was successful,Sometimes
1,2025-01-15 09:35:59.793,Male,>50,Employed,8+ hours,8+ hours,Tiktok,Longer videos (>30 seconds),Longer videos (podcasts etc),Educational,Maybe,> 30 mins,Maybe,Sometimes,Neutral,"No, I dont want to",Sometimes
2,2025-01-15 21:35:57.252,Male,>50,Employed,8+ hours,< 2 hours,Facebook,"Reels (under 20 seconds), Instagram stories","Shorts, Videos (< 10mins)",Educational,Yes,> 30 mins,Yes,No,Entertained,Yes and i was successful,No
3,2025-01-14 23:20:36.563,Male,<20,Student,4-6 hours,< 2 hours,Youtube,Reels (under 20 seconds),Videos (< 10mins),NaN,Maybe,> 30 mins,No,Sometimes,"Relaxed, Neutral",Yes and i was successful,Yes
4,2025-01-15 12:43:58.809,Male,>50,Employed,2-4hours,< 2 hours,Youtube,Longer videos (>30 seconds),Longer videos (podcasts etc),"Latest trends, challenges etc",Yes,10-30mins,No,Yes,Entertained,Yes and i was unsuccessful,Yes

In [3]:
df.shape

(1000, 17)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                                                                                                        Non-Null Count  Dtype
---  ------                                                                                                        --------------  -----
 0   Timestamp                                                                                                     1000 non-null   object
 1   Gender                                                                                                        1000 non-null   object
 2   Age group                                                                                                     1000 non-null   object
 3   Profession                                                                                                    1000 non-null   object
 4   Average screen time on daily basis (phone or laptop)                                                          1000 non-null   object
 5   Average time spent on social media on daily basis                                                             1000 non-null   object
 6   What's your most used social media platform?                                                                  1000 non-null   object
 7   Your content-format preference while using Instagram                                                          1000 non-null   object
 8   Your content-format preference while using Youtube                                                            1000 non-null   object
 9   What kind of content do you prefer?                                                                           989 non-null    object
 10  Do you feel that consuming short-form content has reduced your ability to focus on longer tasks or content?   1000 non-null   object
 11    How long can you stay focused on a task without getting distracted?                                         1000 non-null   object
 12  Do you find it difficult to focus on longer videos or read articles after consuming short-form content?       1000 non-null   object
 13  Do you feel addicted to these platforms and short-length contents?                                            1000 non-null   object
 14  How do you feel after spending time watching short-form videos?                                               1000 non-null   object
 15  Have you ever tried to reduce the time spent on short-form videos?                                            1000 non-null   object
 16  Has it affected your productivity in terms of work and life?                                                  1000 non-null   object
dtypes: object(17)
memory usage: 132.9+ KB

In [5]:
df1=pd.read_csv('student_health.csv')
df1.head()

,Names,Age,Gender,Mobile Phone,Mobile Operating System,Mobile phone use for education,Mobile phone activities,Helpful for studying,Educational Apps,Daily usages,Performance impact,Usage distraction,Attention span,Useful features,Health Risks,Beneficial subject,Usage symptoms,Symptom frequency,Health precautions,Health rating
0,Amir,21-25,Male,Yes,Android,Sometimes,All of these,Yes,Educational Videos,> 6 hours,Neutral,Not Distracting,No,Internet Access,No,Reasarch,Headache,Sometimes,Taking Break during prolonged use,Excellent
1,Iftikhar,21-25,Male,Yes,Android,Sometimes,All of these,No,Language,> 6 hours,Neutral,During Exams,Yes,Calculator,No,Browsing Material,Sleep disturbance,Rarely,Limiting Screen Time,Excellent;Good;Fair;Poor
2,Saleem,21-25,Male,Yes,Android,Sometimes,Social Media;Web-browsing;Messaging;All of these,Yes,Study Planner,2-4 hours,Agree,During Exams,Yes,Internet Access,Yes,Reasarch,Sleep disturbance,Sometimes,Limiting Screen Time,Excellent
3,Jawed,26-30,Male,Yes,Android,Rarely,Web-browsing,Yes,Language,> 6 hours,Agree,During Exams,No,Internet Access,Yes,Reasarch,Anxiety or Stress,Rarely,Limiting Screen Time,Good
4,Aryan,21-25,Male,Yes,Android,Sometimes,All of these,Yes,Educational Videos,2-4 hours,Agree,While Studying,Yes,Internet Access,Yes,Browsing Material,Sleep disturbance,Sometimes,Using Blue light filter,Good

In [6]:
df1.shape

(1000, 20)

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Names                           1000 non-null   object
 1   Age                             1000 non-null   object
 2   Gender                          1000 non-null   object
 3   Mobile Phone                    1000 non-null   object
 4   Mobile Operating System         1000 non-null   object
 5   Mobile phone use for education  979 non-null    object
 6   Mobile phone activities         991 non-null    object
 7   Helpful for studying            977 non-null    object
 8   Educational Apps                985 non-null    object
 9   Daily usages                    991 non-null    object
 10  Performance impact              984 non-null    object
 11  Usage distraction               985 non-null    object
 12  Attention span                  991 non-null    object
 13  Useful features                 987 non-null    object
 14  Health Risks                    972 non-null    object
 15  Beneficial subject              991 non-null    object
 16  Usage symptoms                  980 non-null    object
 17  Symptom frequency               991 non-null    object
 18  Health precautions              991 non-null    object
 19  Health rating                   991 non-null    object
dtypes: object(20)
memory usage: 156.4+ KB

Cleaning survey data

In [8]:
survey_data=df
survey_data.head()

,Timestamp,Gender,Age group,Profession,Average screen time on daily basis (phone or laptop),Average time spent on social media on daily basis,What's your most used social media platform?,Your content-format preference while using Instagram,Your content-format preference while using Youtube,What kind of content do you prefer?,Do you feel that consuming short-form content has reduced your ability to focus on longer tasks or content?,How long can you stay focused on a task without getting distracted?,Do you find it difficult to focus on longer videos or read articles after consuming short-form content?,Do you feel addicted to these platforms and short-length contents?,How do you feel after spending time watching short-form videos?,Have you ever tried to reduce the time spent on short-form videos?,Has it affected your productivity in terms of work and life?
0,2025-01-14 23:49:12.926,Male,20-30,Employed,6-8 hours,< 2 hours,Instagram,Reels (under 20 seconds),Videos (< 10mins),"Entertainment, Comedy",Maybe,5-10 mins,No,Sometimes,Neutral,Yes and i was successful,Sometimes
1,2025-01-15 09:35:59.793,Male,>50,Employed,8+ hours,8+ hours,Tiktok,Longer videos (>30 seconds),Longer videos (podcasts etc),Educational,Maybe,> 30 mins,Maybe,Sometimes,Neutral,"No, I dont want to",Sometimes
2,2025-01-15 21:35:57.252,Male,>50,Employed,8+ hours,< 2 hours,Facebook,"Reels (under 20 seconds), Instagram stories","Shorts, Videos (< 10mins)",Educational,Yes,> 30 mins,Yes,No,Entertained,Yes and i was successful,No
3,2025-01-14 23:20:36.563,Male,<20,Student,4-6 hours,< 2 hours,Youtube,Reels (under 20 seconds),Videos (< 10mins),NaN,Maybe,> 30 mins,No,Sometimes,"Relaxed, Neutral",Yes and i was successful,Yes
4,2025-01-15 12:43:58.809,Male,>50,Employed,2-4hours,< 2 hours,Youtube,Longer videos (>30 seconds),Longer videos (podcasts etc),"Latest trends, challenges etc",Yes,10-30mins,No,Yes,Entertained,Yes and i was unsuccessful,Yes

In [9]:
survey_data.columns = survey_data.columns.str.strip()  # Removes leading/trailing spaces
survey_data.rename(columns={'Average screen time on daily basis (phone or laptop)':'Screen time',
                      'Average time spent on social media on daily basis':'Social Media usage',
                       'What\'s your most used social media platform?':'Fav social media',
                       'Your content-format preference while using Instagram':'Format preference Instagram',
                       'Your content-format preference while using Youtube':'Format preference Youtube',
                       'What kind of content do you prefer?':'Content preference',
                       'Do you feel that consuming short-form content has reduced your ability to focus on longer tasks or content?':'Reduced focus(Yes/No)?',
                       'How long can you stay focused on a task without getting distracted?':'Duration of focus',
                       'Do you find it difficult to focus on longer videos or read articles after consuming short-form content?':'Difficulty focusing(Yes/No)?',
                       'Do you feel addicted to these platforms and short-length contents?':'Addiction (Yes/No)?',
                       'How do you feel after spending time watching short-form videos?':'Happy/Guilty/Relaxed?',
                       'Have you ever tried to reduce the time spent on short-form videos?':'Attempt at reducing addiction (Yes/No)',
                       'Has it affected your productivity in terms of work and life?':'Effect on productivity(Yes/No)?'
                      },inplace=True)
survey_data.head()

,Timestamp,Gender,Age group,Profession,Screen time,Social Media usage,Fav social media,Format preference Instagram,Format preference Youtube,Content preference,Reduced focus(Yes/No)?,Duration of focus,Difficulty focusing(Yes/No)?,Addiction (Yes/No)?,Happy/Guilty/Relaxed?,Attempt at reducing addiction (Yes/No),Effect on productivity(Yes/No)?
0,2025-01-14 23:49:12.926,Male,20-30,Employed,6-8 hours,< 2 hours,Instagram,Reels (under 20 seconds),Videos (< 10mins),"Entertainment, Comedy",Maybe,5-10 mins,No,Sometimes,Neutral,Yes and i was successful,Sometimes
1,2025-01-15 09:35:59.793,Male,>50,Employed,8+ hours,8+ hours,Tiktok,Longer videos (>30 seconds),Longer videos (podcasts etc),Educational,Maybe,> 30 mins,Maybe,Sometimes,Neutral,"No, I dont want to",Sometimes
2,2025-01-15 21:35:57.252,Male,>50,Employed,8+ hours,< 2 hours,Facebook,"Reels (under 20 seconds), Instagram stories","Shorts, Videos (< 10mins)",Educational,Yes,> 30 mins,Yes,No,Entertained,Yes and i was successful,No
3,2025-01-14 23:20:36.563,Male,<20,Student,4-6 hours,< 2 hours,Youtube,Reels (under 20 seconds),Videos (< 10mins),NaN,Maybe,> 30 mins,No,Sometimes,"Relaxed, Neutral",Yes and i was successful,Yes
4,2025-01-15 12:43:58.809,Male,>50,Employed,2-4hours,< 2 hours,Youtube,Longer videos (>30 seconds),Longer videos (podcasts etc),"Latest trends, challenges etc",Yes,10-30mins,No,Yes,Entertained,Yes and i was unsuccessful,Yes

In [10]:
survey_data['Timestamp']=pd.to_datetime(survey_data['Timestamp'])
survey_data['Gender']=survey_data['Gender'].astype('category')
survey_data['Age group']=survey_data['Age group'].astype('category')
survey_data['Profession']=survey_data['Profession'].astype('category')
survey_data['Screen time']=survey_data['Screen time'].astype('category')
survey_data['Fav social media']=survey_data['Fav social media'].astype('category')
survey_data['Format preference Instagram']=survey_data['Format preference Instagram'].astype('category')
survey_data['Format preference Youtube']=survey_data['Format preference Youtube'].astype('category')
survey_data['Content preference']=survey_data['Content preference'].astype('category')
survey_data['Reduced focus(Yes/No)?']=survey_data['Reduced focus(Yes/No)?'].astype('category')
survey_data['Duration of focus']=survey_data['Duration of focus'].astype('category')
survey_data['Difficulty focusing(Yes/No)?']=survey_data['Difficulty focusing(Yes/No)?'].astype('category')
survey_data['Addiction (Yes/No)?']=survey_data['Addiction (Yes/No)?'].astype('category')
survey_data['Happy/Guilty/Relaxed?']=survey_data['Happy/Guilty/Relaxed?'].astype('category')
survey_data['Attempt at reducing addiction (Yes/No)']=survey_data['Attempt at reducing addiction (Yes/No)'].astype('category')
survey_data['Effect on productivity(Yes/No)?']=survey_data['Effect on productivity(Yes/No)?'].astype('category')
survey_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Timestamp                               1000 non-null   datetime64[ns]
 1   Gender                                  1000 non-null   category
 2   Age group                               1000 non-null   category
 3   Profession                              1000 non-null   category
 4   Screen time                             1000 non-null   category
 5   Social Media usage                      1000 non-null   object
 6   Fav social media                        1000 non-null   category
 7   Format preference Instagram             1000 non-null   category
 8   Format preference Youtube               1000 non-null   category
 9   Content preference                      989 non-null    category
 10  Reduced focus(Yes/No)?                  1000 non-null   category
 11  Duration of focus                       1000 non-null   category
 12  Difficulty focusing(Yes/No)?            1000 non-null   category
 13  Addiction (Yes/No)?                     1000 non-null   category
 14  Happy/Guilty/Relaxed?                   1000 non-null   category
 15  Attempt at reducing addiction (Yes/No)  1000 non-null   category
 16  Effect on productivity(Yes/No)?         1000 non-null   category
dtypes: category(15), datetime64[ns](1), object(1)
memory usage: 34.2+ KB

In [11]:
survey_data.isna().sum()

Timestamp                                  0
Gender                                     0
Age group                                  0
Profession                                 0
Screen time                                0
Social Media usage                         0
Fav social media                           0
Format preference Instagram                0
Format preference Youtube                  0
Content preference                        11
Reduced focus(Yes/No)?                     0
Duration of focus                          0
Difficulty focusing(Yes/No)?               0
Addiction (Yes/No)?                        0
Happy/Guilty/Relaxed?                      0
Attempt at reducing addiction (Yes/No)     0
Effect on productivity(Yes/No)?            0
dtype: int64

In [12]:
survey_data['Content preference']=survey_data['Content preference'].fillna(survey_data['Content preference'].mode()[0])
survey_data.isna().sum()

Timestamp                                 0
Gender                                    0
Age group                                 0
Profession                                0
Screen time                               0
Social Media usage                        0
Fav social media                          0
Format preference Instagram               0
Format preference Youtube                 0
Content preference                        0
Reduced focus(Yes/No)?                    0
Duration of focus                         0
Difficulty focusing(Yes/No)?              0
Addiction (Yes/No)?                       0
Happy/Guilty/Relaxed?                     0
Attempt at reducing addiction (Yes/No)    0
Effect on productivity(Yes/No)?           0
dtype: int64

Feature engineering

In [13]:
survey_data['Year']=survey_data['Timestamp'].dt.year
survey_data.head()

,Timestamp,Gender,Age group,Profession,Screen time,Social Media usage,Fav social media,Format preference Instagram,Format preference Youtube,Content preference,Reduced focus(Yes/No)?,Duration of focus,Difficulty focusing(Yes/No)?,Addiction (Yes/No)?,Happy/Guilty/Relaxed?,Attempt at reducing addiction (Yes/No),Effect on productivity(Yes/No)?,Year
0,2025-01-14 23:49:12.926,Male,20-30,Employed,6-8 hours,< 2 hours,Instagram,Reels (under 20 seconds),Videos (< 10mins),"Entertainment, Comedy",Maybe,5-10 mins,No,Sometimes,Neutral,Yes and i was successful,Sometimes,2025
1,2025-01-15 09:35:59.793,Male,>50,Employed,8+ hours,8+ hours,Tiktok,Longer videos (>30 seconds),Longer videos (podcasts etc),Educational,Maybe,> 30 mins,Maybe,Sometimes,Neutral,"No, I dont want to",Sometimes,2025
2,2025-01-15 21:35:57.252,Male,>50,Employed,8+ hours,< 2 hours,Facebook,"Reels (under 20 seconds), Instagram stories","Shorts, Videos (< 10mins)",Educational,Yes,> 30 mins,Yes,No,Entertained,Yes and i was successful,No,2025
3,2025-01-14 23:20:36.563,Male,<20,Student,4-6 hours,< 2 hours,Youtube,Reels (under 20 seconds),Videos (< 10mins),"Entertainment, Comedy",Maybe,> 30 mins,No,Sometimes,"Relaxed, Neutral",Yes and i was successful,Yes,2025
4,2025-01-15 12:43:58.809,Male,>50,Employed,2-4hours,< 2 hours,Youtube,Longer videos (>30 seconds),Longer videos (podcasts etc),"Latest trends, challenges etc",Yes,10-30mins,No,Yes,Entertained,Yes and i was unsuccessful,Yes,2025

In [14]:
survey_data.drop('Timestamp',inplace=True,axis=1)
survey_data.head()

,Gender,Age group,Profession,Screen time,Social Media usage,Fav social media,Format preference Instagram,Format preference Youtube,Content preference,Reduced focus(Yes/No)?,Duration of focus,Difficulty focusing(Yes/No)?,Addiction (Yes/No)?,Happy/Guilty/Relaxed?,Attempt at reducing addiction (Yes/No),Effect on productivity(Yes/No)?,Year
0,Male,20-30,Employed,6-8 hours,< 2 hours,Instagram,Reels (under 20 seconds),Videos (< 10mins),"Entertainment, Comedy",Maybe,5-10 mins,No,Sometimes,Neutral,Yes and i was successful,Sometimes,2025
1,Male,>50,Employed,8+ hours,8+ hours,Tiktok,Longer videos (>30 seconds),Longer videos (podcasts etc),Educational,Maybe,> 30 mins,Maybe,Sometimes,Neutral,"No, I dont want to",Sometimes,2025
2,Male,>50,Employed,8+ hours,< 2 hours,Facebook,"Reels (under 20 seconds), Instagram stories","Shorts, Videos (< 10mins)",Educational,Yes,> 30 mins,Yes,No,Entertained,Yes and i was successful,No,2025
3,Male,<20,Student,4-6 hours,< 2 hours,Youtube,Reels (under 20 seconds),Videos (< 10mins),"Entertainment, Comedy",Maybe,> 30 mins,No,Sometimes,"Relaxed, Neutral",Yes and i was successful,Yes,2025
4,Male,>50,Employed,2-4hours,< 2 hours,Youtube,Longer videos (>30 seconds),Longer videos (podcasts etc),"Latest trends, challenges etc",Yes,10-30mins,No,Yes,Entertained,Yes and i was unsuccessful,Yes,2025

In [15]:
student_span=df1
student_span.head()

,Names,Age,Gender,Mobile Phone,Mobile Operating System,Mobile phone use for education,Mobile phone activities,Helpful for studying,Educational Apps,Daily usages,Performance impact,Usage distraction,Attention span,Useful features,Health Risks,Beneficial subject,Usage symptoms,Symptom frequency,Health precautions,Health rating
0,Amir,21-25,Male,Yes,Android,Sometimes,All of these,Yes,Educational Videos,> 6 hours,Neutral,Not Distracting,No,Internet Access,No,Reasarch,Headache,Sometimes,Taking Break during prolonged use,Excellent
1,Iftikhar,21-25,Male,Yes,Android,Sometimes,All of these,No,Language,> 6 hours,Neutral,During Exams,Yes,Calculator,No,Browsing Material,Sleep disturbance,Rarely,Limiting Screen Time,Excellent;Good;Fair;Poor
2,Saleem,21-25,Male,Yes,Android,Sometimes,Social Media;Web-browsing;Messaging;All of these,Yes,Study Planner,2-4 hours,Agree,During Exams,Yes,Internet Access,Yes,Reasarch,Sleep disturbance,Sometimes,Limiting Screen Time,Excellent
3,Jawed,26-30,Male,Yes,Android,Rarely,Web-browsing,Yes,Language,> 6 hours,Agree,During Exams,No,Internet Access,Yes,Reasarch,Anxiety or Stress,Rarely,Limiting Screen Time,Good
4,Aryan,21-25,Male,Yes,Android,Sometimes,All of these,Yes,Educational Videos,2-4 hours,Agree,While Studying,Yes,Internet Access,Yes,Browsing Material,Sleep disturbance,Sometimes,Using Blue light filter,Good

In [16]:
student_span.columns=student_span.columns.str.strip()
student_span.drop(columns=['Mobile Operating System','Educational Apps','Beneficial subject'],axis=1,inplace=True)

In [17]:
student_span.columns=student_span.columns.str.strip()
student_span['Age']=student_span['Age'].astype('category')
student_span['Gender']=student_span['Gender'].astype('category')
student_span['Mobile Phone']=student_span['Mobile Phone'].astype('category')
student_span['Mobile phone use for education']=student_span['Mobile phone use for education'].astype('category')
student_span['Helpful for studying']=student_span['Helpful for studying'].astype('category')
student_span['Daily usages']=student_span['Daily usages'].astype('category')
student_span['Performance impact']=student_span['Performance impact'].astype('category')
student_span['Usage distraction']=student_span['Usage distraction'].astype('category')
student_span['Attention span']=student_span['Attention span'].astype('category')
student_span['Useful features']=student_span['Useful features'].astype('category')
student_span['Health Risks']=student_span['Health Risks'].astype('category')
student_span['Symptom frequency']=student_span['Symptom frequency'].astype('category')
student_span['Health precautions']=student_span['Health precautions'].astype('category')
student_span['Health rating']=student_span['Health rating'].astype('category')
student_span['Usage symptoms']=student_span['Usage symptoms'].astype('category')
student_span['Mobile phone activities']=student_span['Mobile phone activities'].astype('category')

student_span.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Names                           1000 non-null   object
 1   Age                             1000 non-null   category
 2   Gender                          1000 non-null   category
 3   Mobile Phone                    1000 non-null   category
 4   Mobile phone use for education  979 non-null    category
 5   Mobile phone activities         991 non-null    category
 6   Helpful for studying            977 non-null    category
 7   Daily usages                    991 non-null    category
 8   Performance impact              984 non-null    category
 9   Usage distraction               985 non-null    category
 10  Attention span                  991 non-null    category
 11  Useful features                 987 non-null    category
 12  Health Risks                    972 non-null    category
 13  Usage symptoms                  980 non-null    category
 14  Symptom frequency               991 non-null    category
 15  Health precautions              991 non-null    category
 16  Health rating                   991 non-null    category
dtypes: category(16), object(1)
memory usage: 26.7+ KB

In [18]:
student_span.drop('Names',inplace=True,axis=1)

In [19]:
student_span.isna().sum()

Age                                0
Gender                             0
Mobile Phone                       0
Mobile phone use for education    21
Mobile phone activities            9
Helpful for studying              23
Daily usages                       9
Performance impact                16
Usage distraction                 15
Attention span                     9
Useful features                   13
Health Risks                      28
Usage symptoms                    20
Symptom frequency                  9
Health precautions                 9
Health rating                      9
dtype: int64

In [20]:
student_span['Mobile phone use for education']=student_span['Mobile phone use for education'].fillna(student_span['Mobile phone use for education'].mode()[0])
student_span['Mobile phone activities']=student_span['Mobile phone activities'].fillna(student_span['Mobile phone activities'].mode()[0])
student_span['Helpful for studying']=student_span['Helpful for studying'].fillna(student_span['Helpful for studying'].mode()[0])
student_span['Performance impact']=student_span['Performance impact'].fillna(student_span['Performance impact'].mode()[0])
student_span['Usage distraction']=student_span['Usage distraction'].fillna(student_span['Usage distraction'].mode()[0])
student_span['Attention span']=student_span['Attention span'].fillna(student_span['Attention span'].mode()[0])
student_span['Useful features']=student_span['Useful features'].fillna(student_span['Useful features'].mode()[0])
student_span['Health Risks']=student_span['Health Risks'].fillna(student_span['Health Risks'].mode()[0])
student_span['Usage symptoms']=student_span['Usage symptoms'].fillna(student_span['Usage symptoms'].mode()[0])
student_span['Daily usages']=student_span['Daily usages'].fillna(student_span['Daily usages'].mode()[0])
student_span['Symptom frequency']=student_span['Symptom frequency'].fillna(student_span['Symptom frequency'].mode()[0])
student_span['Health precautions']=student_span['Health precautions'].fillna(student_span['Health precautions'].mode()[0])
student_span['Health rating']=student_span['Health rating'].fillna(student_span['Health rating'].mode()[0])
student_span.isna().sum()

Age                               0
Gender                            0
Mobile Phone                      0
Mobile phone use for education    0
Mobile phone activities           0
Helpful for studying              0
Daily usages                      0
Performance impact                0
Usage distraction                 0
Attention span                    0
Useful features                   0
Health Risks                      0
Usage symptoms                    0
Symptom frequency                 0
Health precautions                0
Health rating                     0
dtype: int64

In [21]:
student_span['Year']='2024'
student_span.head()

,Age,Gender,Mobile Phone,Mobile phone use for education,Mobile phone activities,Helpful for studying,Daily usages,Performance impact,Usage distraction,Attention span,Useful features,Health Risks,Usage symptoms,Symptom frequency,Health precautions,Health rating,Year
0,21-25,Male,Yes,Sometimes,All of these,Yes,> 6 hours,Neutral,Not Distracting,No,Internet Access,No,Headache,Sometimes,Taking Break during prolonged use,Excellent,2024
1,21-25,Male,Yes,Sometimes,All of these,No,> 6 hours,Neutral,During Exams,Yes,Calculator,No,Sleep disturbance,Rarely,Limiting Screen Time,Excellent;Good;Fair;Poor,2024
2,21-25,Male,Yes,Sometimes,Social Media;Web-browsing;Messaging;All of these,Yes,2-4 hours,Agree,During Exams,Yes,Internet Access,Yes,Sleep disturbance,Sometimes,Limiting Screen Time,Excellent,2024
3,26-30,Male,Yes,Rarely,Web-browsing,Yes,> 6 hours,Agree,During Exams,No,Internet Access,Yes,Anxiety or Stress,Rarely,Limiting Screen Time,Good,2024
4,21-25,Male,Yes,Sometimes,All of these,Yes,2-4 hours,Agree,While Studying,Yes,Internet Access,Yes,Sleep disturbance,Sometimes,Using Blue light filter,Good,2024

In [22]:
#Demographic for survey data
survey_data['Age group'].unique()

['20-30', '>50', '<20', '30-40', '40-50', '30-40, 40-50, >50']
Categories (6, object): ['20-30', '30-40', '30-40, 40-50, >50', '40-50', '<20', '>50']

In [23]:
survey_data.drop(survey_data[survey_data['Age group'].isin(["30-40, 40-50, >50"])].index, inplace=True)

In [24]:
#Demographic for survey data
survey_data['Age group'].unique()

['20-30', '>50', '<20', '30-40', '40-50']
Categories (6, object): ['20-30', '30-40', '30-40, 40-50, >50', '40-50', '<20', '>50']

In [25]:
#demographic for student data
survey_data['Age group'].value_counts()

Age group
20-30                454
40-50                209
>50                  148
30-40                120
<20                   66
30-40, 40-50, >50      0
Name: count, dtype: int64

In [26]:
student_span['Age'].value_counts()

Age
21-25    733
16-20    128
26-30     91
31-35     48
Name: count, dtype: int64

In [27]:
student_span['Gender'].value_counts()

Gender
Male      831
Female    169
Name: count, dtype: int64

In [28]:
student_span['Gender'].value_counts()

Gender
Male      831
Female    169
Name: count, dtype: int64

In [29]:
survey_data['Social Media usage'].value_counts()

Social Media usage
< 2 hours    467
2-4 hours    359
4-6hours     129
8+ hours      30
6-8 hours     12
Name: count, dtype: int64

In [30]:
survey_data['Format preference Instagram'].value_counts()

Format preference Instagram
Reels (under 20 seconds)                                                    506
Longer videos (>30 seconds)                                                 205
Reels (under 20 seconds), Instagram stories                                 117
Longer videos (>30 seconds), Reels (under 20 seconds)                        75
Instagram stories                                                            53
Longer videos (>30 seconds), Reels (under 20 seconds), Instagram stories     34
Longer videos (>30 seconds), Instagram stories                                7
Name: count, dtype: int64

In [31]:
survey_data['Format preference Youtube'].value_counts()

Format preference Youtube
Videos (< 10mins)                                          340
Longer videos (podcasts etc)                               213
Shorts                                                     186
Videos (< 10mins), Longer videos (podcasts etc)            113
Shorts, Videos (< 10mins)                                   94
Shorts, Videos (< 10mins), Longer videos (podcasts etc)     36
Shorts, Longer videos (podcasts etc)                        15
Name: count, dtype: int64

In [32]:
survey_data.to_csv('final_survey.csv',index=False)

In [33]:
student_span.to_csv('final_student_survey.csv',index=False)

In [34]:
survey_data.head()

,Gender,Age group,Profession,Screen time,Social Media usage,Fav social media,Format preference Instagram,Format preference Youtube,Content preference,Reduced focus(Yes/No)?,Duration of focus,Difficulty focusing(Yes/No)?,Addiction (Yes/No)?,Happy/Guilty/Relaxed?,Attempt at reducing addiction (Yes/No),Effect on productivity(Yes/No)?,Year
0,Male,20-30,Employed,6-8 hours,< 2 hours,Instagram,Reels (under 20 seconds),Videos (< 10mins),"Entertainment, Comedy",Maybe,5-10 mins,No,Sometimes,Neutral,Yes and i was successful,Sometimes,2025
1,Male,>50,Employed,8+ hours,8+ hours,Tiktok,Longer videos (>30 seconds),Longer videos (podcasts etc),Educational,Maybe,> 30 mins,Maybe,Sometimes,Neutral,"No, I dont want to",Sometimes,2025
2,Male,>50,Employed,8+ hours,< 2 hours,Facebook,"Reels (under 20 seconds), Instagram stories","Shorts, Videos (< 10mins)",Educational,Yes,> 30 mins,Yes,No,Entertained,Yes and i was successful,No,2025
3,Male,<20,Student,4-6 hours,< 2 hours,Youtube,Reels (under 20 seconds),Videos (< 10mins),"Entertainment, Comedy",Maybe,> 30 mins,No,Sometimes,"Relaxed, Neutral",Yes and i was successful,Yes,2025
4,Male,>50,Employed,2-4hours,< 2 hours,Youtube,Longer videos (>30 seconds),Longer videos (podcasts etc),"Latest trends, challenges etc",Yes,10-30mins,No,Yes,Entertained,Yes and i was unsuccessful,Yes,2025

In [35]:
student_span.head()

,Age,Gender,Mobile Phone,Mobile phone use for education,Mobile phone activities,Helpful for studying,Daily usages,Performance impact,Usage distraction,Attention span,Useful features,Health Risks,Usage symptoms,Symptom frequency,Health precautions,Health rating,Year
0,21-25,Male,Yes,Sometimes,All of these,Yes,> 6 hours,Neutral,Not Distracting,No,Internet Access,No,Headache,Sometimes,Taking Break during prolonged use,Excellent,2024
1,21-25,Male,Yes,Sometimes,All of these,No,> 6 hours,Neutral,During Exams,Yes,Calculator,No,Sleep disturbance,Rarely,Limiting Screen Time,Excellent;Good;Fair;Poor,2024
2,21-25,Male,Yes,Sometimes,Social Media;Web-browsing;Messaging;All of these,Yes,2-4 hours,Agree,During Exams,Yes,Internet Access,Yes,Sleep disturbance,Sometimes,Limiting Screen Time,Excellent,2024
3,26-30,Male,Yes,Rarely,Web-browsing,Yes,> 6 hours,Agree,During Exams,No,Internet Access,Yes,Anxiety or Stress,Rarely,Limiting Screen Time,Good,2024
4,21-25,Male,Yes,Sometimes,All of these,Yes,2-4 hours,Agree,While Studying,Yes,Internet Access,Yes,Sleep disturbance,Sometimes,Using Blue light filter,Good,2024